# -*- mode: snippet -*-
# name: catch
# key: .catch
# --
.catch((err): void => { console.warn(\`${1:Exception}: \$\{err\}\`) })$2